config/routes.rb
UrlShortenerApp::Application.routes.draw do

  as :user do
    match 'sign_in' => 'devise/sessions#new'
    match 'sign_out' => 'devise/sessions#destroy'
  end
  
  devise_for :users
  
  resources :users
  resources :links
  
  root to: "links#new"


  match ':short_url' => 'link_redirects#show'
end

app/models/hit.rb
# == Schema Information
#
# Table name: hits
#
#  id         :integer          not null, primary key
#  link_id    :integer
#  ip_address :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Hit < ActiveRecord::Base
  attr_accessible :ip_address, :link_id
  
  belongs_to :link
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id           :integer          not null, primary key
#  original_url :string(255)
#  short_url    :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :integer
#

class Link < ActiveRecord::Base
  attr_accessible :original_url, :short_url, :user_id
  belongs_to :user
  has_many :hits
  
  before_save { self.short_url.downcase! }
  before_save :undesirable_words
  before_save :vanity_url_check
  before_save :clean_up_url
  
  validates :short_url, uniqueness: { case_sensitive: false }
  
  private
  
    def undesirable_words
      undesirable_words = ["hate", "bad", "fuck", "shit", "bitch"]
      if undesirable_words.include?(self.short_url)
        self.short_url = ""
      else
        self.short_url = self.short_url
      end
    end
    
    def vanity_url_check
      if self.short_url.empty?
        random_string = (0...8).map{65.+(rand(25)).chr}.join
        self.short_url = random_string
      else
        self.short_url = self.short_url
      end
    end
    
    def clean_up_url
      base_url = "http://"
      if self.original_url =~ /https?/
       self.original_url
      else
        self.original_url = base_url + self.original_url
      end
    end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name
  has_many :links
  
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/link_redirects_controller.rb
class LinkRedirectsController < ApplicationController
  
  def show
    @link = Link.find_by_short_url!(params[:short_url])
    remote_ip = request.remote_ip
    Hit.create(:link_id => @link.id, :ip_address => remote_ip)
    
    redirect_to @link.original_url
  end
  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController  
  def index
    @links = Link.all
  end
  
  def new
    @link = Link.new
  end
  
  def create
    
    @link = Link.new(:original_url => params[:link][:original_url],
                     :short_url => params[:link][:short_url], 
                     :user_id => current_user.id)
    if @link.save
      redirect_to user_path(current_user)
    else
      flash[:error] = "You have an issue with your definded Short URL"
      render 'new'
    end
  end
  
  def show
    @base_url = root_url
    @link = Link.find(params[:id])
  end
  
  def destroy
    user = Link.find(params[:id]).user_id
    Link.find(params[:id]).destroy
    redirect_to user_path(user)
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
    @links = @user.links.all
    @base_url = root_url
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
require 'rest_client'
require 'open-uri'
require 'json'

module LinksHelper

  def country_finder(ip_address)
    response = RestClient.get("http://api.hostip.info/get_html.php", 
                              :params => { :ip => "#{ip_address}" })
    response.split("\n").first
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortenerApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <% flash.each do |key, msg| %>
    <p><%= msg %></p>
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>


</body>
</html>

app/views/links/new.html.erb
<%= form_for(@link) do |f| %>
  
  <%= f.label :original_url %>
  <%= f.text_field :original_url %>

  <%= f.label :short_url %>
  <%= f.text_field :short_url %>
  
  <%#= f.label :user_id %>
  <%#= f.text_field :user_id %>

  <%= f.submit "Create Short URL" %>
  
<% end %>

<% if user_signed_in? %>
  <p><%= link_to "My Short URLs", user_path(current_user) %></p>
  <p><%= link_to "Sign Out", destroy_user_session_path, :method => 'delete' %></p>
<% else %>
  <p><%= link_to "Sign In", new_user_session_path %></p>
<% end %>

app/views/links/show.html.erb
<h1> Standard URL Shortener</h1>
<% full_url = root_url + @link.short_url %>
<p><%= full_url %></p>

<p>goes to:</p>

<p><%= @link.original_url %></p>

<br />
<h1>Short URL Stats:</h1>
<p>This short URL has had <%= @link.hits.count %> hits</p>
<p>The vistits are from these IP Addresses:</p>
<% @link.hits.each do |hit| %>
  <p><%= hit.ip_address %> from country: <%= country_finder(hit.ip_address) %></p>
  
<% end %>

app/views/shared/_errors.html.erb
<div class="flash">
  <%= <span class="error">flash[:error]</span> %>
</div>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= link_to "Sign Out", sign_out_path %>

<p><%= link_to "Create a New URL", new_link_path %></p>

<div class="row">
  <table>
    <tr>
      <th class="span4">Short URL</th>
      <th class="span1">Points to</th>
      <th class="span4">Original URL</th>
      <th class="span1">Delete</th>
      <th class="span1">Show</th>
    </tr>
    <% @links.each do |link| %>
      <div class="row"
        <tr>
          <% full_url = @base_url + link.short_url %>
          <td class="span4"><%= link_to full_url , full_url %></td>
          <td class="span1">--></td>
          <td class="span4"><%= link.original_url %></td>
          <td class="span1">
            <%= link_to "Delete", link, method: 'delete', data: {confirm: 'Are you Sure?'} %>
          </td>
          <td class="span1"><%= link_to "Stats", link_path(link) %></td>
        </tr>
      </div>
    <% end %> 
  </table>
</div>